from enum import Enum


class TaskInfoTaskType(str, Enum):
    BOOKDROP_PERIODIC_SCANNING = "BOOKDROP_PERIODIC_SCANNING"
    CLEANUP_DELETED_BOOKS = "CLEANUP_DELETED_BOOKS"
    CLEANUP_TEMP_METADATA = "CLEANUP_TEMP_METADATA"
    REFRESH_LIBRARY_METADATA = "REFRESH_LIBRARY_METADATA"
    REFRESH_METADATA_MANUAL = "REFRESH_METADATA_MANUAL"
    SYNC_LIBRARY_FILES = "SYNC_LIBRARY_FILES"
    UPDATE_BOOK_RECOMMENDATIONS = "UPDATE_BOOK_RECOMMENDATIONS"

    def __str__(self) -> str:
        return str(self.value)
